# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Alex Popescu (@pspsalex)


sensor:
  - id: !extend env2
    temperature:
      on_value:
        then:
          - lvgl.label.update:
              id: temperature
              text:
                format: "%.1f°C"
                args: [ 'x' ]

    humidity:
      on_value:
        then:
          - lvgl.label.update:
              id: humidity
              text:
                format: "%.1f%%"
                args: [ 'x' ]



lvgl:
  pages:
    - id: main_page
      widgets:
        - obj:
            align: CENTER
            width: 240
            styles:
              - clean_obj
            layout:
              type: FLEX
              flex_flow: COLUMN
              flex_align_main: SPACE_BETWEEN
              flex_align_cross: CENTER
              flex_align_track: CENTER
            widgets:
              - label:
                  id: temperature
                  text: "--.-°C"
                  text_font: roboto_48_num_bold
                  text_color: 0x338833
              - label:
                  id: humidity
                  text: "--.- %%"
                  text_font: roboto_32
                  text_color: 0x338833


        - image:
            id: img_status_net
            align: TOP_MID
            src: image_wifi_unknown_small
        - image:
            id: img_status_ha
            align: BOTTOM_MID
            src: image_cloud_off_small
