# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Alex Popescu (@pspsalex)

packages:
  # Include the common images for all themes
  common_images: !include ../../images.yaml

  # Include the generated images for this theme
  generated_images: !include images.gen.yaml

# Define any theme-specific images here:
image:
  defaults:
    type: ${display_image_type}
    byte_order: ${display_byte_order}
    transparency: alpha_channel

  images:
    - file: "assets/images/esphome_logo_dark.svg"
      id: boot_logo
      resize: 220x44
