# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Alex Popescu (@pspsalex)

packages:
  # Include the common images for all themes
  common_images: !include ../../images.yaml

  # Include the generated images for this theme
  generated_images: !include images.gen.yaml

# Define any theme-specific images here:
image:
  - file: "assets/images/esphome_logo_dark.svg"
    id: boot_logo
    resize: 597x117
    type: RGB565
    transparency: alpha_channel

  - file: "assets/3rdparty/sc/sc_shutter_open_135.png"
    id: shutter_open
    type: RGB565
    transparency: alpha_channel

  - file: "assets/3rdparty/sc/sc_shutter_slide_135.png"
    id: shutter_slide
    type: RGB565
    transparency: alpha_channel
