# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Alex Popescu (@pspsalex)

# Custom icons / image configurations can be added here.
#
# These will be included in all themes, so use with care.
#
# Example:
# image:
#   - name: custom_icon
#     file: custom_icon.png
#     size: 32x32
#     color: white
