# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Alex Popescu (@pspsalex)

packages:
  icons: !include
    file: ../icons.yaml
    vars:
      theme: default

  base: !include
    file: _base.yaml
    vars:
      lvgl_color_fg: "0x000000"
      lvgl_color_bg: "0xFFFFFF"
      lvgl_border_w_normal: "1"
      lvgl_border_w_pressed: "3"
      lvgl_border_w_disabled: "0"
      lvgl_border_w_focused: "1"
      lvgl_border_w_edit: "2"
      lvgl_padding_default: "4"
      default_font: "roboto_18"

image:
  - file: "assets/images/esphome_logo.svg"
    id: boot_logo
    resize: 597x117
    type: RGB565
    transparency: alpha_channel
